// lib/models/pharmacist.dart

class Pharmacist {
  final String? id; // Will be generated by the backend (DB ID)
  final String pharmacyName;
  final String email;
  final String licenceNumber;
  final String contactNumber;
  final String address;

  Pharmacist({
    this.id,
    required this.pharmacyName,
    required this.email,
    required this.licenceNumber,
    required this.contactNumber,
    required this.address,
  });

  // Method to convert the model into a JSON map for API submission (Backend)
  Map<String, dynamic> toJson() {
    return {
      'pharmacyName': pharmacyName,
      'email': email,
      'licenceNumber': licenceNumber,
      'contactNumber': contactNumber,
      'address': address,
    };
  }

  // Method to create the model from a JSON map (e.g., received after successful registration)
  factory Pharmacist.fromJson(Map<String, dynamic> json) {
    return Pharmacist(
      id: json['id'] as String?,
      pharmacyName: json['pharmacyName'] as String,
      email: json['email'] as String,
      licenceNumber: json['licenceNumber'] as String,
      contactNumber: json['contactNumber'] as String,
      address: json['address'] as String,
    );
  }
}